import os
import sys
import subprocess
from pathlib import Path

# Template for generating C++ resource creation code
HEADER_TEMPLATE = '''\
#pragma once
#include "graphics_pipeline/ShaderResource.h"
#include <memory>

class {class_name} {{
  public:
    static std::unique_ptr<graphics_pipeline::ShaderResource> create_resource();
}};
'''

CPP_TEMPLATE = '''\
/// This file is auto generated by compile_assets.py
#include "{header_name}"

namespace {{
{xxd_content}
}} // namespace

std::unique_ptr<graphics_pipeline::ShaderResource> {class_name}::create_resource() {{
    return graphics_pipeline::ShaderResourceBuilder()
        .name("{resource_name}")
        .length({var_name}_len)
        .bytes(&{var_name}[0])
        .build();
}}'''

def compile_shader(glslc_path, script_dir, shader_name, stage):
    """Compile a GLSL shader to SPIR-V."""
    input_file = script_dir / f"{shader_name}.glsl"
    output_file = script_dir / f"{shader_name}.spv"
    
    cmd = [
        str(glslc_path),
        f"-fshader-stage={stage}",
        str(input_file),
        "-o",
        str(output_file),
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"Shader compilation failed for: {shader_name}.glsl")
        print(result.stderr)
        return False
    
    return True

def run_xxd(conf):
    """Run xxd to convert binary SPIR-V to C array."""
    # cmd = ["xxd", "-i", str(spv_file), str(output_c_file)]
    cmd = ["xxd",
           "-n", str(conf["xxd_variable_name"]),
            "-i", str(conf["location"] / conf["input_file"])
           ]
    
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    
    if result.returncode != 0:
        print(f"xxd failed for: {conf["input_file"]}")
        print(result.stderr)
        return False

    header_content = HEADER_TEMPLATE.format(
            class_name=conf["class_name"]
        )

    with open(conf["location"] / conf["output_h_file"], 'w') as f:
        f.write(header_content)

    cpp_content = CPP_TEMPLATE.format(
            header_name=conf["output_h_file"],
            resource_name=conf["resource_name"],
            xxd_content=result.stdout,
            class_name=conf["class_name"],
            var_name=conf["xxd_variable_name"]
        )

    with open(conf["location"] / conf["output_cpp_file"], 'w') as f:
        f.write(cpp_content)

    
    return True

def main():
    # Get script directory
    script_dir = Path(__file__).parent.resolve()
    
    # Path to glslc compiler
    glslc_path = Path("/Users/adamolsson/VulkanSDK/1.3.296.0/macOS/bin/glslc")
    
    print("Compiling quad shaders...")
    
    # Compile vertex shader
    if not compile_shader(glslc_path, script_dir, "quad_vertex", "vert"):
        sys.exit(1)
    
    # Compile fragment shader
    if not compile_shader(glslc_path, script_dir, "quad_fragment", "frag"):
        sys.exit(1)
    
    # Run xxd on compiled shaders
    print("Converting quad shaders to C files...")
    # Convert vertex shader
    conf = {
        "location": script_dir,
        "input_file": "quad_vertex.spv",
        "output_cpp_file": "quad_vertex_shader.cpp",
        "output_h_file": "quad_vertex_shader.h",
        "resource_name": "QuadVertexShader",
        "xxd_variable_name": "quad_vertex_bytes",
        "class_name": "QuadVertexShader",
    }
    if not run_xxd(conf):
        sys.exit(1)
    
    # Convert fragment shader
    conf = {
        "location": script_dir,
        "input_file": "quad_fragment.spv",
        "output_cpp_file": "quad_fragment_shader.cpp",
        "output_h_file": "quad_fragment_shader.h",
        "resource_name": "QuadFragmentShader",
        "xxd_variable_name": "quad_fragment_bytes",
        "class_name": "QuadFragmentShader",
    }
    if not run_xxd(conf):
        sys.exit(1)
    
    print("Compiling quad shaders... OK!")
    return 0

if __name__ == "__main__":
    sys.exit(main())
